variable "region" {}
variable "account_environment" {}
variable "dns_name" {}
variable "availability_zones" {}
variable "ami_type" {}
variable "disk_size" {}
variable "instance_types" {}
variable "desired_size" {}
variable "max_size" {}
variable "min_size" {}
variable "public_hosted_zone" {}
variable "alb_certificate" {}
